// Generated by voice_kws/tools/export_c_array.py on 2026-09-17.
// Do not edit by hand: regenerate after training so the board and the report
// describe the same model.

// =========================================================================
//  PLACEHOLDER MODEL -- TRAINED ON SYNTHETIC DATA
//  Generated from tools/make_synthetic.py output, which is not speech. This
//  build will not recognise anyone. Record real clips, retrain, and
//  regenerate these files before any test, demo or reported number.
// =========================================================================

#pragma once

#include <stdint.h>

// ---------------------------------------------------------------- audio ---
#define KWS_SAMPLE_RATE        16000
#define KWS_CLIP_MS            1000
#define KWS_CLIP_SAMPLES       16000

// Push-to-talk captures longer than one window so three overlapping windows
// can vote; see kws_vote() in the firmware.
#define KWS_PTT_CAPTURE_MS     1400
#define KWS_PTT_CAPTURE_SAMPLES 22400
#define KWS_NUM_WINDOWS        3
static const int kKwsWindowOffsetMs[KWS_NUM_WINDOWS] = { 0, 200, 400 };

// ------------------------------------------------------------- frontend ---
// These must match kws/config.py exactly. The FrontendConfig built from them
// is reset before every capture, because the TF op the training features came
// from always starts from a clean noise/PCAN state.
#define KWS_WINDOW_SIZE_MS     30
#define KWS_WINDOW_STEP_MS     20
#define KWS_NUM_CHANNELS       40
#define KWS_LOWER_BAND_LIMIT   125.0f
#define KWS_UPPER_BAND_LIMIT   7500.0f
#define KWS_SMOOTHING_BITS     10
#define KWS_EVEN_SMOOTHING     0.025f
#define KWS_ODD_SMOOTHING      0.06f
#define KWS_MIN_SIGNAL_REMAIN  0.05f
#define KWS_ENABLE_PCAN        1
#define KWS_PCAN_STRENGTH      0.95f
#define KWS_PCAN_OFFSET        80.0f
#define KWS_GAIN_BITS          21
#define KWS_ENABLE_LOG         1
#define KWS_SCALE_SHIFT        6

#define KWS_NUM_FRAMES         49
#define KWS_FEATURE_ELEMENTS   1960

// uint16 frontend output -> uint8 -> int8, integer maths only:
//   v = ((raw * KWS_VALUE_SCALE) + KWS_VALUE_DIV/2) / KWS_VALUE_DIV
//   clamp 0..255, then subtract 128.
#define KWS_VALUE_SCALE        256
#define KWS_VALUE_DIV          666

// ---------------------------------------------------------------- model ---
#define KWS_NUM_CLASSES        4
#define KWS_MODEL_BYTES        44480

// Input quantisation is scale=1.0, zero_point=0,
// so the int8 feature bytes go straight into the input tensor unchanged.
#define KWS_INPUT_SCALE        1.0f
#define KWS_INPUT_ZERO_POINT   0

// probability = (q - KWS_OUTPUT_ZERO_POINT) * KWS_OUTPUT_SCALE
#define KWS_OUTPUT_SCALE       0.00390625f
#define KWS_OUTPUT_ZERO_POINT  -128

// Chosen by evaluate.py's threshold sweep against the false-trigger budget.
#define KWS_CONF_THRESHOLD     0.94f

// --------------------------------------------------------------- labels ---
// Index order is the LoRa command id. Append new keywords, never insert.
static const char *const kKwsLabels[KWS_NUM_CLASSES] = {
    "silence",
    "unknown",
    "help",
    "evacuate"
};
static const char *const kKwsLabelsZh[KWS_NUM_CLASSES] = {
    "静音",
    "未知",
    "救命",
    "撤离"
};

// Classes that must never raise an alarm, whatever the confidence.
#define KWS_NUM_NON_COMMAND    2
static const int kKwsNonCommand[KWS_NUM_NON_COMMAND] = { 0, 1 };

static inline int kws_is_command(int label_id) {
  for (int i = 0; i < KWS_NUM_NON_COMMAND; i++) {
    if (kKwsNonCommand[i] == label_id) return 0;
  }
  return label_id >= 0 && label_id < KWS_NUM_CLASSES;
}
