// Generated by voice_kws/tools/export_c_array.py on 2026-09-17.
// Do not edit by hand: regenerate after training so the board and the report
// describe the same model.

// =========================================================================
//  PLACEHOLDER MODEL -- TRAINED ON SYNTHETIC DATA
//  Generated from tools/make_synthetic.py output, which is not speech. This
//  build will not recognise anyone. Record real clips, retrain, and
//  regenerate these files before any test, demo or reported number.
// =========================================================================

#pragma once

extern const unsigned char g_kws_model_data[];
extern const unsigned int g_kws_model_data_len;
