#!/usr/bin/env python3
"""Export decision-logic test vectors from Python for the host C test.

    python tools/export_test_vectors.py

Writes firmware/voice_node/test/kws_test_vectors.h. The C test replays these
through kws_postprocess.c and fails on any disagreement, which is what keeps
the board's decision rule identical to the one the reported metrics used.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

import numpy as np

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from kws import config as C, postprocess as pp  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DEST = ROOT.parent / "firmware" / "voice_node" / "test"


def feature_cases() -> list[int]:
    """Frontend outputs spanning the clamp edges and the rounding boundaries."""
    cases = [0, 1, 2, 332, 333, 334, 665, 666, 667, 999, 1000, 1332, 1665,
             32767, 65535]
    cases += [int(v) for v in np.linspace(0, 2000, 41)]
    cases += [int(v) for v in np.random.default_rng(3).integers(0, 65536, 64)]
    return sorted(set(cases))


def vote_cases(n: int = 400) -> list[np.ndarray]:
    rng = np.random.default_rng(11)
    cases: list[np.ndarray] = []

    # Hand-picked shapes: unanimous, 2-1 split, three-way disagreement,
    # a command just under and just over the threshold, and ties.
    q_at = lambda p: int(round(p / pp.OUTPUT_SCALE + pp.OUTPUT_ZERO_POINT))
    thr = _threshold()
    cases += [
        np.array([[127, -128, -128, -128]] * 3, np.int8),               # silence x3
        np.array([[-128, -128, 127, -128]] * 3, np.int8),               # help x3
        np.array([[-128, -128, 127, -128], [-128, -128, 127, -128],
                  [-128, 127, -128, -128]], np.int8),                   # 2-1
        np.array([[127, -128, -128, -128], [-128, 127, -128, -128],
                  [-128, -128, 127, -128]], np.int8),                   # 3-way
        np.array([[-128, -128, q_at(thr), -128]] * 3, np.int8),         # exactly at
        np.array([[-128, -128, q_at(thr) - 1, -128]] * 3, np.int8),     # just under
        np.array([[0, 0, 0, 0]] * 3, np.int8),                          # all tied
    ]

    shape = (len(C.WINDOW_OFFSETS_MS), C.NUM_CLASSES)
    for _ in range(n):
        cases.append(rng.integers(-128, 128, size=shape, dtype=np.int64)
                     .astype(np.int8))
    return cases


def _threshold() -> float:
    import json
    p = ROOT / "out" / "report" / "threshold.json"
    if p.exists():
        return float(json.loads(p.read_text())["threshold"])
    return C.DEFAULT_CONF_THRESHOLD


def main() -> int:
    thr = _threshold()
    feats = feature_cases()
    votes = vote_cases()

    feat_rows = "\n".join(
        f"    {{ {raw}u, {pp.quantize_feature(raw)} }}," for raw in feats)

    def c_float(x: float) -> str:
        """C float literal: "0" would become "0f", which is not valid C."""
        t = f"{x:.9g}"
        if "." not in t and "e" not in t and "E" not in t:
            t += ".0"
        return t + "f"

    vote_rows = []
    for case in votes:
        r = pp.vote(case, thr)
        windows = ", ".join(
            "{" + ", ".join(str(int(v)) for v in row) + "}" for row in case)
        vote_rows.append(
            f"    {{ {{{windows}}}, {r.label}, {r.votes}, "
            f"{c_float(r.confidence)}, {1 if r.accepted else 0} }},")

    DEST.mkdir(parents=True, exist_ok=True)
    (DEST / "kws_test_vectors.h").write_text(f"""// Generated by voice_kws/tools/export_test_vectors.py on {date.today()}.
// Expected values come from kws/postprocess.py, the implementation the
// reported metrics were computed with.
#pragma once

#include <stdint.h>

#include "../kws_config.h"

typedef struct {{
  uint16_t raw;
  int8_t expected;
}} KwsFeatureVector;

typedef struct {{
  int8_t window_out[KWS_NUM_WINDOWS][KWS_NUM_CLASSES];
  int expected_label;
  int expected_votes;
  float expected_confidence;
  int expected_accepted;
}} KwsVoteVector;

#define KWS_TEST_THRESHOLD {c_float(thr)}

static const KwsFeatureVector kKwsFeatureVectors[] = {{
{feat_rows}
}};
#define KWS_NUM_FEATURE_VECTORS \\
    (int)(sizeof(kKwsFeatureVectors) / sizeof(kKwsFeatureVectors[0]))

static const KwsVoteVector kKwsVoteVectors[] = {{
{chr(10).join(vote_rows)}
}};
#define KWS_NUM_VOTE_VECTORS \\
    (int)(sizeof(kKwsVoteVectors) / sizeof(kKwsVoteVectors[0]))
""", encoding="utf-8")

    print(f"[vectors] {DEST / 'kws_test_vectors.h'}")
    print(f"[vectors] {len(feats)} feature cases, {len(votes)} vote cases, "
          f"threshold {thr}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
