#!/usr/bin/env python3
"""Emit the firmware artefacts: model C array, config header, label table.

    python tools/export_c_array.py
    python tools/export_c_array.py --dest ../firmware/voice_node

Everything written here is derived from kws/config.py and out/report/, so the
board cannot drift away from the model that was trained and measured.  Re-run
it after every quantize.py / evaluate.py.
"""

from __future__ import annotations

import argparse
import json
from datetime import date
from pathlib import Path

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from kws import config as C  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_DEST = ROOT.parent / "firmware" / "voice_node"

BANNER = """// Generated by voice_kws/tools/export_c_array.py on {today}.
// Do not edit by hand: regenerate after training so the board and the report
// describe the same model.
"""


def c_array(data: bytes, name: str, per_line: int = 12) -> str:
    lines = []
    for i in range(0, len(data), per_line):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + per_line])
        lines.append("    " + chunk + ",")
    body = "\n".join(lines)
    return (f"alignas(16) const unsigned char {name}[] = {{\n{body}\n}};\n"
            f"const unsigned int {name}_len = {len(data)};\n")


SYNTHETIC_STAMP = """
// =========================================================================
//  PLACEHOLDER MODEL -- TRAINED ON SYNTHETIC DATA
//  Generated from tools/make_synthetic.py output, which is not speech. This
//  build will not recognise anyone. Record real clips, retrain, and
//  regenerate these files before any test, demo or reported number.
// =========================================================================
"""


def write_model(tflite: Path, dest: Path, today: str,
                synthetic: bool = False) -> int:
    data = tflite.read_bytes()
    stamp = SYNTHETIC_STAMP if synthetic else ""
    (dest / "kws_model_data.h").write_text(
        BANNER.format(today=today) + stamp + """
#pragma once

extern const unsigned char g_kws_model_data[];
extern const unsigned int g_kws_model_data_len;
""", encoding="utf-8")
    (dest / "kws_model_data.cc").write_text(
        BANNER.format(today=today) + stamp
        + '\n#include "kws_model_data.h"\n\n'
        + c_array(data, "g_kws_model_data"), encoding="utf-8")
    return len(data)


def write_config(dest: Path, today: str, quant: dict, thresh: dict,
                 synthetic: bool = False) -> None:
    f = C.FRONTEND
    labels_c = ",\n    ".join(f'"{x}"' for x in C.LABELS)
    labels_zh = ",\n    ".join(f'"{x}"' for x in C.LABELS_ZH)
    non_cmd = ", ".join(str(i) for i in C.NON_COMMAND_IDS)
    offsets = ", ".join(str(x) for x in C.WINDOW_OFFSETS_MS)
    threshold = thresh.get("threshold", C.DEFAULT_CONF_THRESHOLD)
    budget_note = "" if thresh.get("budget_met", True) else (
        "\n// WARNING: this threshold did NOT meet the false-trigger budget when\n"
        "// it was measured. Treat any demo built on it as provisional.\n")

    (dest / "kws_config.h").write_text(
        BANNER.format(today=today) + (SYNTHETIC_STAMP if synthetic else "")
        + f"""{budget_note}
#pragma once

#include <stdint.h>

// ---------------------------------------------------------------- audio ---
#define KWS_SAMPLE_RATE        {C.SAMPLE_RATE}
#define KWS_CLIP_MS            {C.CLIP_MS}
#define KWS_CLIP_SAMPLES       {C.CLIP_SAMPLES}

// Push-to-talk captures longer than one window so three overlapping windows
// can vote; see kws_vote() in the firmware.
#define KWS_PTT_CAPTURE_MS     {C.PTT_CAPTURE_MS}
#define KWS_PTT_CAPTURE_SAMPLES {C.SAMPLE_RATE * C.PTT_CAPTURE_MS // 1000}
#define KWS_NUM_WINDOWS        {len(C.WINDOW_OFFSETS_MS)}
static const int kKwsWindowOffsetMs[KWS_NUM_WINDOWS] = {{ {offsets} }};

// ------------------------------------------------------------- frontend ---
// These must match kws/config.py exactly. The FrontendConfig built from them
// is reset before every capture, because the TF op the training features came
// from always starts from a clean noise/PCAN state.
#define KWS_WINDOW_SIZE_MS     {f['window_size']}
#define KWS_WINDOW_STEP_MS     {f['window_step']}
#define KWS_NUM_CHANNELS       {f['num_channels']}
#define KWS_LOWER_BAND_LIMIT   {f['lower_band_limit']}f
#define KWS_UPPER_BAND_LIMIT   {f['upper_band_limit']}f
#define KWS_SMOOTHING_BITS     {f['smoothing_bits']}
#define KWS_EVEN_SMOOTHING     {f['even_smoothing']}f
#define KWS_ODD_SMOOTHING      {f['odd_smoothing']}f
#define KWS_MIN_SIGNAL_REMAIN  {f['min_signal_remaining']}f
#define KWS_ENABLE_PCAN        {int(f['enable_pcan'])}
#define KWS_PCAN_STRENGTH      {f['pcan_strength']}f
#define KWS_PCAN_OFFSET        {f['pcan_offset']}f
#define KWS_GAIN_BITS          {f['gain_bits']}
#define KWS_ENABLE_LOG         {int(f['enable_log'])}
#define KWS_SCALE_SHIFT        {f['scale_shift']}

#define KWS_NUM_FRAMES         {C.NUM_FRAMES}
#define KWS_FEATURE_ELEMENTS   {C.FEATURE_BYTES}

// uint16 frontend output -> uint8 -> int8, integer maths only:
//   v = ((raw * KWS_VALUE_SCALE) + KWS_VALUE_DIV/2) / KWS_VALUE_DIV
//   clamp 0..255, then subtract 128.
#define KWS_VALUE_SCALE        {C.VALUE_SCALE}
#define KWS_VALUE_DIV          {C.VALUE_DIV}

// ---------------------------------------------------------------- model ---
#define KWS_NUM_CLASSES        {C.NUM_CLASSES}
#define KWS_MODEL_BYTES        {quant.get('tflite_bytes', 0)}

// Input quantisation is scale={quant.get('input_scale', 1.0)}, zero_point={quant.get('input_zero_point', 0)},
// so the int8 feature bytes go straight into the input tensor unchanged.
#define KWS_INPUT_SCALE        {quant.get('input_scale', 1.0)}f
#define KWS_INPUT_ZERO_POINT   {quant.get('input_zero_point', 0)}

// probability = (q - KWS_OUTPUT_ZERO_POINT) * KWS_OUTPUT_SCALE
#define KWS_OUTPUT_SCALE       {quant.get('output_scale', 1.0 / 256)}f
#define KWS_OUTPUT_ZERO_POINT  {quant.get('output_zero_point', -128)}

// Chosen by evaluate.py's threshold sweep against the false-trigger budget.
#define KWS_CONF_THRESHOLD     {threshold}f

// --------------------------------------------------------------- labels ---
// Index order is the LoRa command id. Append new keywords, never insert.
static const char *const kKwsLabels[KWS_NUM_CLASSES] = {{
    {labels_c}
}};
static const char *const kKwsLabelsZh[KWS_NUM_CLASSES] = {{
    {labels_zh}
}};

// Classes that must never raise an alarm, whatever the confidence.
#define KWS_NUM_NON_COMMAND    {len(C.NON_COMMAND_IDS)}
static const int kKwsNonCommand[KWS_NUM_NON_COMMAND] = {{ {non_cmd} }};

static inline int kws_is_command(int label_id) {{
  for (int i = 0; i < KWS_NUM_NON_COMMAND; i++) {{
    if (kKwsNonCommand[i] == label_id) return 0;
  }}
  return label_id >= 0 && label_id < KWS_NUM_CLASSES;
}}
""", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--tflite", type=Path, default=ROOT / "out" / "kws_int8.tflite")
    ap.add_argument("--dest", type=Path, default=DEFAULT_DEST)
    args = ap.parse_args()

    if not args.tflite.exists():
        raise SystemExit(f"{args.tflite} not found -- run quantize.py first")

    report = ROOT / "out" / "report"
    quant = json.loads((report / "quantization.json").read_text()) \
        if (report / "quantization.json").exists() else {}
    thresh = json.loads((report / "threshold.json").read_text()) \
        if (report / "threshold.json").exists() else {}
    prov = json.loads((report / "provenance.json").read_text()) \
        if (report / "provenance.json").exists() else {}
    synthetic = bool(prov.get("synthetic", False))
    if not thresh:
        print("[warn] no threshold.json -- falling back to config.DEFAULT_CONF_THRESHOLD")

    args.dest.mkdir(parents=True, exist_ok=True)
    today = date.today().isoformat()
    n = write_model(args.tflite, args.dest, today, synthetic)
    write_config(args.dest, today, quant, thresh, synthetic)

    print(f"[export] {args.dest / 'kws_model_data.cc'}  ({n / 1024:.1f} KB model)")
    print(f"[export] {args.dest / 'kws_config.h'}")
    print(f"[export] threshold {thresh.get('threshold', C.DEFAULT_CONF_THRESHOLD)}"
          + ("" if thresh.get("budget_met", True) else "  (BUDGET NOT MET)"))
    if synthetic:
        print("[export] stamped PLACEHOLDER: this model was trained on "
              "synthetic data")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
