#pragma once

// Copy this file to onenet_secrets.h and fill in your own values.
static const char *WIFI_SSID = "YOUR_WIFI_SSID";
static const char *WIFI_PASSWORD = "YOUR_WIFI_PASSWORD";
static const char *ONENET_PRODUCT_ID = "YOUR_PRODUCT_ID";
static const char *ONENET_DEVICE_NAME = "YOUR_DEVICE_NAME";
static const char *ONENET_DEVICE_SECRET = "YOUR_DEVICE_SECRET";
// Optional: a complete Token generated by OneNET. Leave empty to generate it
// dynamically from ONENET_DEVICE_SECRET after NTP synchronization.
static const char *ONENET_DEVICE_TOKEN = "";
